### ISSUE TITLE
Retrofit Deferred return

### ISSUE THREAD

**Issue by antonkazakov** [allash/android-coroutines#6]
https://github.com/allash/android-coroutines/blob/c84e1d49da1caa85308e8a9442ee9804e111f80e/app/src/main/java/com/example/android/coroutineshomework/network/ApiService.kt#L11

Лучше оперировать Deferred в качестве ретурн тайпа. Для этого можно либо поднять версию Retrofit где есть встроенная поддержка корутин, либо использовать https://github.com/JakeWharton/retrofit2-kotlin-coroutines-adapter / свою реализацию адаптера.

**Comment by allash** [comment]
Не совсем понял про Deferred. Как я понял, плагин retrofit2-kotlin-coroutines-adapter теперь deprecated и Deferred уже можно заменить на suspend и обычный Response<>. Вот пример миграции Plaid 
https://github.com/android/plaid/commit/94d5a415ff0cc3794cee8dd7a34d48d4984cbf0c
